import ApiError from "./ApiError";

const catchAsync = (fn)=>{
    return async (req,res,next)=>{
        try {
            await fn(req,res,next)
        } catch (error) {
           return next(error)
        }
    }
}

export default catchAsync;